### ISSUE TITLE
Code style checker

### ISSUE THREAD

**Issue by adaamz** [planette/nettecamp.cz#21]
Co jsem koukal tak se podařilo namixovat mezery a taby v jednom souboru.
Aby to bylo konzistentní tak bych byl pro aby se do CI přidal nějakej code style checker.
Ale teď je otázka jaký? ninjify/qa, doctrine/cs, slevomat/cs, consistence/cs?

Klidně se potom pustím do přidání do projektu + fixnutí errorů, ale chtělo by to vybrat nějakej ruleset ;-).

**Comment by chemix** [comment]
To by bylo super. Asi cesta https://contributte.org/ninjify/ ? s tim, ze jsem pro mezery oproti tabum.
