### ISSUE TITLE
nahradit ublaboo/mailing za contribute/mailing

### ISSUE THREAD

**Issue by chemix** [planette/nettecamp.cz#25]
Posilaji se dva emaily, jeden na admina a jeden ucastnikovi. Zbavime se jedne tridy ktera je jen prenoskou pro email. Contributte mailing akceptuje obycejne pole.

**Comment by TonnyJe** [comment]
Pokud šlo o třídu 'RegistrationData', tak díky vyřešení Issue #26 tato třída zmizela. 
Jako třída poslaná do Maileru klidně může být použita entitní třída 'Registration' stačilo jí přidat implementaci 'IMessageData' rozhraní a tedy přepravka již více není potřeba a na vše máme jednu třídu.

**Comment by chemix** [comment]
Hlavne jde o contributte/mailing. Ta trida s tim spojena je fajn, ale docasne reseni.

**Comment by chemix** [comment]
done: https://github.com/planette/nettecamp.cz/commit/7f4ab4aa61bfb9f8148c9db88730f92f7e43d4bf
