### ISSUE TITLE
phpstan

### ISSUE THREAD

**Issue by chemix** [planette/nettecamp.cz#8]
pridat nastaveni a spoustec pro phpstan. Aspon minimalni level

**Comment by iGavrilo** [comment]
Koncom tohto týždňa viem poslať PR. Len mi dajte vedieť či sa na to chystá niekto iný alebo nie :)

**Comment by chemix** [comment]
Jdi do toho.... mas predstavu jak? Tak nejak? 

https://github.com/planette/componette.com/blob/master/composer.json#L87-L89

https://github.com/planette/componette.com/blob/master/phpstan.neon

**Comment by iGavrilo** [comment]
Jo pridám tam aj makefile nech je to o niečo pohodlnejšie :)

**Comment by chemix** [comment]
ping @iGavrilo mas to nejak rozpracovane?

**Comment by chemix** [comment]
zaklad pro php stan je online 5b8e7d52ce2bd79f14fbe777859cf3c5d071c670 
bezime na level 1 s nette extension

co dal? 

Level 2 ?

**Comment by adaamz** [comment]
Dál třeba update na phpstan 0.12(.3)? Večír bych se na to mohl kouknout.

btw phpstan bych spíš dal do composer sekce require-dev, než do require :-)

**Comment by chemix** [comment]
@adaamz ja myslim, ze "require-dev" se zbytecne precenuje :-)

**Comment by adaamz** [comment]
Můžeme zavřít? :-)
