### ISSUE TITLE
strict_types

### ISSUE THREAD

**Issue by chemix** [planette/nettecamp.cz#9]
pridat do aplikace strict types

**Comment by chemix** [comment]
aplikace ted ma vsude potřebné declare(strict_types=1);

dava smysl nekam doplnovat navic typy?

**Comment by vojtamares** [comment]
@chemix určitě, IDE ti pak líp napovídá (pokud tam už nejsou anotace).

V #24 CodeFixer (CodeSniffer) doplnil řadu type hintů a return type hintů sám, někde jsem to doplnil já ručně, protože CodeSnifferu to vadilo že tam nejsou. Ale to je tím že jsem použil výchozí (Contributte) ruleset, který je dost přísný.
